\ fhdl.builder.4th
\ V3: Поддержка signed и reg (Attributes)

\ ==========================================================
\ 1. Хранилище данных
\ ==========================================================

100 constant MAX_PORTS
32  constant NAME_LIMIT

create mod-name-buf 256 allot
variable mod-defined   0 mod-defined !

\ Массивы свойств портов
create p-names  MAX_PORTS NAME_LIMIT * allot 
create p-widths MAX_PORTS cells allot
create p-types  MAX_PORTS cells allot  \ 0=input, 1=output, 2=inout
create p-attrs  MAX_PORTS cells allot  \ Битовая маска: 1=reg, 2=signed

variable port-count    0 port-count !

\ Временные флаги для текущего определения
variable is-reg        0 is-reg !
variable is-signed     0 is-signed !

\ ==========================================================
\ 2. Вспомогательная логика
\ ==========================================================

: reset-builder
    0 mod-defined !
    0 port-count !
    0 is-reg !
    0 is-signed ! ;

: get-name-addr ( index -- addr )
    NAME_LIMIT * p-names + ;

: register-port ( width type -- )
    port-count @ MAX_PORTS >= IF
        cr s" [ERROR] Too many ports!" type cr bye
    THEN

    >r >r ( R: type width )
    
    \ Сохраняем имя
    port-count @ get-name-addr place
    
    \ Сохраняем ширину и тип
    r> port-count @ cells p-widths + !
    r> port-count @ cells p-types + !

    \ Сохраняем атрибуты (bit0=reg, bit1=signed)
    is-reg @ 
    is-signed @ 2 * + 
    port-count @ cells p-attrs + !

    \ Сбрасываем флаги и увеличиваем счетчик
    0 is-reg !
    0 is-signed !
    1 port-count +! 
;

\ ==========================================================
\ 3. DSL - Словарь разметки
\ ==========================================================

warnings off

: module: ( "name" -- )
    parse-name mod-name-buf place
    1 mod-defined !
    0 port-count ! ;

\ --- Модификаторы ---
\ Устанавливают флаг только для СЛЕДУЮЩЕГО определения

: reg    1 is-reg ! ;
: signed 1 is-signed ! ;

\ --- Определения портов ---

: input: 
    parse-name 1 0 register-port ;

: output: 
    parse-name 1 1 register-port ;

: inout:
    parse-name 1 2 register-port ;

: input-bus:
    parse-name          
    parse-name evaluate 
    0 register-port ;

: output-bus:
    parse-name          
    parse-name evaluate 
    1 register-port ;

: inout-bus:
    parse-name          
    parse-name evaluate 
    2 register-port ;

: end-module ;

warnings on

\ ==========================================================
\ 4. Генератор Verilog
\ ==========================================================

: .width ( width -- )
    dup 1 > IF ." [" 1- 0 .r ." :0] " ELSE drop ." " THEN ;

: .dir ( type -- )
    dup 0 = IF ." input "  drop EXIT THEN
    dup 1 = IF ." output " drop EXIT THEN
    dup 2 = IF ." inout "  drop EXIT THEN
    drop ." wire " ;

\ Печать атрибутов (reg, signed)
: .attrs ( attr -- )
    \ Проверяем бит 0 (reg)
    dup 1 and IF ." reg " THEN
    \ Проверяем бит 1 (signed)
    2 and IF ." signed " THEN ;

: gen-header-ports
    port-count @ 0 ?DO
        i get-name-addr count type
        i port-count @ 1- < IF ." , " THEN
    LOOP
;

: gen-decl-ports
    port-count @ 0 ?DO
        cr ."   "
        \ 1. Направление (input/output)
        i cells p-types + @ .dir
        
        \ 2. Атрибуты (reg signed)
        i cells p-attrs + @ .attrs

        \ 3. Ширина ([7:0])
        i cells p-widths + @ .width

        \ 4. Имя
        i get-name-addr count type
        ." ;"
    LOOP
;

: generate-verilog
    cr s" // Generated by FHDL" type cr
    
    s" module " type
    mod-name-buf count type
    s"  (" type 
    gen-header-ports 
    s" );" type       
    
    gen-decl-ports
    cr
    
    s" endmodule" type cr
;

\ ==========================================================
\ 5. Точка входа
\ ==========================================================

: run-build ( addr u -- )
    reset-builder

    2dup file-status nip 0= IF
        cr s" [BUILDER] Parsing file: " type 2dup type cr
        ['] included catch dup IF
            cr s" [ERROR] Error parsing file. Code: " type . cr
            2drop drop EXIT
        THEN
        drop
        
        mod-defined @ IF
            generate-verilog
        ELSE
            cr s" [ERROR] No 'module:' found." type cr
        THEN
    ELSE
        cr s" [ERROR] File not found: " type type cr
    THEN
;

