\ fhdl.builder.4th
\ FHDL Builder V2

require fhdl.structs.4th

\ ==========================================================
\ 1. Глобальное состояние
\ ==========================================================

variable modules-head
variable modules-tail
variable current-module 

: reset-builder
    0 modules-head !
    0 modules-tail !
    0 current-module ! ;

\ ==========================================================
\ 2. Конструктор
\ ==========================================================

: module, ( name-addr name-u -- )
    module% allocate throw >r
    0 r@ mod.next !
    str-dup r@ mod.name-len ! r@ mod.name-addr !
    modules-head modules-tail r@ list-append
    r> current-module !
;

\ Отключаем предупреждения, так как name есть в старых версиях Gforth
warnings off
: name ( "name" -- addr u ) parse-name ;
warnings on

\ ==========================================================
\ 3. Генератор
\ ==========================================================

: gen-one-module ( node-addr -- )
    >r
    cr s" module " type 
    r@ mod.name-addr @ r@ mod.name-len @ type
    s"  ();" type cr
    s" endmodule" type cr
    r> drop
;

: generate-verilog, ( -- )
    modules-head @ 0= IF 
        cr s" [WARN] No modules defined." type cr EXIT 
    THEN
    cr s" // Generated by FHDL V2" type cr
    modules-head @ 
    BEGIN dup WHILE
        dup >r gen-one-module r> mod.next @
    REPEAT drop
;

\ ==========================================================
\ 4. Деструктор
\ ==========================================================

: free-modules ( -- )
    modules-head @
    BEGIN dup WHILE
        dup mod.next @ >r
        dup mod.name-addr @ over mod.name-len @ str-free
        free throw
        r>
    REPEAT drop
    reset-builder
;

: run-build ( addr u -- )
    reset-builder
    2dup file-status nip 0= IF
        cr s" [BUILDER] Parsing file: " type 2dup type cr
        ['] included catch dup IF
            cr s" [ERROR] Error parsing file. Code: " type . cr
            2drop drop EXIT
        THEN
        drop
    ELSE
        cr s" [ERROR] File not found: " type type cr
    THEN
;

