\ fhdl.builder.4th
require fhdl.structs.4th

variable modules-head
variable modules-tail
variable current-module 

\ Хелперы
: (.) ( n -- addr u ) s>d <# #s #> ;
warnings off
: name ( "text" -- addr u ) parse-name ;
: value ( "text" -- addr u ) parse-name ;
warnings on

: reset-builder
    0 modules-head ! 0 modules-tail ! 0 current-module ! ;

\ ==========================================================
\ Конструктор
\ ==========================================================

: module, ( name-addr name-u -- )
    module% allocate throw >r
    0 r@ mod.next !
    str-dup r@ mod.name-len ! r@ mod.name-addr !
    
    0 r@ mod.params-head ! 0 r@ mod.params-tail !
    0 r@ mod.ports-head !  0 r@ mod.ports-tail !
    0 r@ mod.assigns-head ! 0 r@ mod.assigns-tail !
    
    modules-head modules-tail r@ list-append
    r> current-module !
;

\ --- Параметры ---

: (param-new) ( val-u val-a name-u name-a -- node-addr )
    current-module @ 0= IF true abort" Error: No module defined." THEN
    param% allocate throw >r
    0 r@ param.next !
    str-dup r@ param.name-len ! r@ param.name-addr !
    str-dup r@ param.val-len !  r@ param.val-addr !
    
    current-module @ mod.params-head current-module @ mod.params-tail r@ list-append
    r> 
;

: parameter, ( val-addr val-u name-addr name-u -- )
    (param-new) 
    0 swap param.is-local ! \ Флаг 0
;

: localparam, ( val-addr val-u name-addr name-u -- )
    (param-new)
    1 swap param.is-local ! \ Флаг 1
;

: param-int, ( n name-addr name-u -- )
    rot (.) 2swap parameter, ;

\ ==========================================================
\ Генератор (Simple Line Style)
\ ==========================================================

: gen-params ( mod-addr -- )
    dup mod.params-head @ 0= IF drop EXIT THEN
    
    cr
    mod.params-head @ 
    BEGIN dup WHILE ( node )
        dup >r
        
        \ Отступ
        ."      "
        
        \ Ключевое слово
        r@ param.is-local @ IF ." localparam " ELSE ." parameter  " THEN
        
        \ Имя = Значение
        r@ param.name-addr @ r@ param.name-len @ type
        ."  = "
        r@ param.val-addr @  r@ param.val-len @  type
        
        \ Точка с запятой и новая строка
        ." ;" cr
        
        r> param.next @
    REPEAT drop
;

: gen-one-module ( node-addr -- )
    >r
    cr s" module " type 
    r@ mod.name-addr @ r@ mod.name-len @ type
    s"  ( );" type cr
    
    r@ gen-params
    
    s" endmodule" type cr
    r> drop
;

: generate-verilog, ( -- )
    modules-head @ 0= IF cr s" [WARN] No modules." type cr EXIT THEN
    cr s" // Generated by FHDL V2" type cr
    modules-head @ BEGIN dup WHILE dup >r gen-one-module r> mod.next @ REPEAT drop
;

\ ==========================================================
\ Очистка
\ ==========================================================

: free-params ( mod-addr -- )
    mod.params-head @ BEGIN dup WHILE
        dup param.next @ >r
        dup param.name-addr @ over param.name-len @ str-free
        dup param.val-addr  @ over param.val-len  @ str-free
        free throw r>
    REPEAT drop ;

: free-modules ( -- )
    modules-head @ BEGIN dup WHILE
        dup mod.next @ >r
        dup free-params
        dup mod.name-addr @ over mod.name-len @ str-free
        free throw r>
    REPEAT drop
    reset-builder ;

: run-build ( addr u -- )
    reset-builder
    2dup file-status nip 0= IF
        cr s" // [BUILDER] Parsing file: " type 2dup type cr
        ['] included catch dup IF cr s" // [ERROR] Parsing failed: " type . cr 2drop drop EXIT THEN drop
    ELSE cr s" // [ERROR] File not found: " type type cr THEN ;

    